# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: newdee.keepane
PackageVersion: 0.30.1
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- keepane
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/newdee/keepane/releases/download/v0.30.1/keepane-0.30.1-windows-x86_64.msi
  InstallerSha256: 50FB9B64949703B85CB39CF0AF92DFD75DFEC9AFAFF1A90F196442633CEE78A1
  ProductCode: '{B325B216-314D-41E4-8624-3071408A4705}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/newdee/keepane/releases/download/v0.30.1/keepane-0.30.1-windows-x86_64-user.msi
  InstallerSha256: F203A78597F55949E5052B55CCC353149EB5B32A8C019D79A4870558ABF3E760
  ProductCode: '{4AABDDDB-1C18-4169-B8EE-219FB55EC8D2}'
ManifestType: installer
ManifestVersion: 1.12.0
