# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: newdee.keepane
PackageVersion: 0.35.4
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- keepane
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/newdee/keepane/releases/download/v0.35.4/keepane-0.35.4-windows-x86_64.msi
  InstallerSha256: D2DBEAC4AD141F9C15320001D09A03932343750AED4702F60F3041D92C3A438D
  ProductCode: '{8401F0EA-C7A2-44CC-B279-72E8593C4DBA}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/newdee/keepane/releases/download/v0.35.4/keepane-0.35.4-windows-x86_64-user.msi
  InstallerSha256: 4D5CB171F2A2A562DFC3C4A9121DEB53FE42BE04B7134B6E3AD2E2D77C9E1A9A
  ProductCode: '{D25E1D8D-89D3-4661-98B1-E31A228B3FD1}'
ManifestType: installer
ManifestVersion: 1.12.0
